version: '3.3'

services:
  mongo:
    image: mongo:3.4
    volumes:
      - ./.neon/mongo/data/db:/data/db
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
#  redis:
#    image: redis:latest
#    volumes:
#      - ./.neon/redis/data:/data
#    ports:
#      - 6379:6379
#    expose:
#      - 6379
#    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: neon
      RABBITMQ_DEFAULT_PASS: neon123
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    restart: always
  neon:
    build: .
    depends_on:
      - mongo
      - redis
      - rabbitmq
    volumes:
      - ./.neon/logs:/app/logs
    environment:
      MODE: init
      APP_SEED_URL: http://www.allitebooks.com
      APP_MAX_DEPTH: 100
      APP_LOG_DIR: /app/logs/
      MQ_HOST: rabbitmq
      MQ_PORT: 5672
      MQ_LOGIN: neon
      MQ_PASSWORD: neon123
      MQ_TIMEOUT: 10000
      MQ_QUEUE: neon
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: neon
      RDS_HOST: redis
      RDS_PORT: 6379
      RDS_WAIT_QUEUE: neon-wait
      RDS_RESULT_QUEUE: neon-results
    restart: always
